config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  root to: 'home#index'

  get '/about' => 'home#about'
  get '/players' => 'players#index'
  get '/players/:username' => 'players#show'

  mount RubyGameHub::API => '/api'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :player
end

app/models/comrade.rb
class Comrade < ActiveRecord::Base
  belongs_to :player
end

app/models/played_with.rb
class PlayedWith < ActiveRecord::Base
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_length_of :username, minimum: 3, maximum: 15
  validates_format_of :username, with: /\A\w+\z/, message: "is invalid (Only letters and numbers)"

  has_many :activities, dependent: :destroy
  has_many :comrades, dependent: :destroy
  # has_many :inverse_comrades, through: :comrades, primary_key: :comrade_id, dependent: :destroy
  has_many :played_withs, dependent: :destroy

  before_destroy do
    Comrade.where("comrade_id = #{self.id}").each {|e| e.destroy}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if player_signed_in?
      # TODO: include friends activities
      @activities = current_player.activities
    end
  end

  def about
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.where(username: params[:username]).first
    @activities = @player.activities
    # @comrades = @player.comrades # Friended initially, @player.id == @comrade.player_id
    @comrades = Comrade.where("player_id = #{@player.id} AND accepted = 't' OR comrade_id = #{@player.id} AND accepted = 't'")
    @comrade_requests = Comrade.where("comrade_id = #{@player.id} AND accepted = 'f'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/home/about.html.slim
h1 Home#about
p Find me in app/views/home/about.html.slim

app/views/home/index.html.slim
- if player_signed_in?
  = render "home/part/activity"
- else
  = render "home/part/intro"

app/views/home/part/_activity.html.slim
-# Please! Make me work. I do not want to be static anymore. :(
h2 Recent Activity
- @activities.each do |activity|
  h4 #{activity.player.username.capitalize} #{activity.event} #{activity.description} with #{'peoples'}
  p=Time.parse(activity.created_at.to_s).strftime('%H:%M %B %e %Y')

app/views/home/part/_intro.html.slim
h1 =RubyGameHub.hub_name
p Compete and play with your friends.

app/views/layouts/application.html.slim
doctype html
html
  head
    title =RubyGameHub.hub_name
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #container
      .header
        h1 =RubyGameHub.hub_name
        a class="button" href="/" Main
        a class="button" href="/#servers" Servers
        a class="button" href="/players" Players
        a class="button" href="/#search" Search
        br
        -# Make me work, please. I hate being functionless!
        p <i class="fa fa-users info" title="Online players"> 12</i> <i class="fa fa-gamepad info" title="Active games"> 3</i> <i class="fa fa-clock-o info" title="Average wait time (in seconds)"> 63.7</i> <i class="fa fa-spinner info" title="Players in queue"> 0</i>
        -# if player_signed_in?
        - if defined?(flash[:notice])
          p.notice #{flash[:notice]}
        - if defined?(flash[:error])
          p.error #{flash[:error]}
        - if defined?(flash[:alert])
          p.error #{flash[:alert]}

        br
      .content
        .sidebar
          - if player_signed_in?
            a href="/players/#{current_player.username}"
              img src=gravatar_image_url(current_player.email, size: 198) alt=current_player.username.humanize
            = link_to current_player.username.humanize, "/players/#{current_player.username}", class: "nav-button"
            = link_to "Account", edit_player_registration_path, class: "nav-button"
            = link_to "Sign Out", destroy_player_session_path, class: "nav-button", method: "delete"
            .friends
              h3 Comrades
              - if current_player
                - Comrade.where("player_id = #{current_player.id} AND accepted = 't' OR comrade_id = #{current_player.id} AND accepted = 't'").each do |comrade|
                  - player = Player.find(comrade.comrade_id) unless current_player.id == comrade.comrade_id
                  - player = Player.find(comrade.player_id) if current_player.id == comrade.comrade_id
                  p
                    i class="fa fa-circle online info" title="Online"
                    a href="/players/#{player.username}" #{player.username}
          - else
            = link_to "Sign Up", new_player_registration_path, class: "nav-button"
            = link_to "Sign In", new_player_session_path, class: "nav-button-bottom"
        #content
          == yield
          br
      .footer
        p =RubyGameHub.hub_footer

app/views/players/index.html.slim
h1 Players
- @players.each do |player|
  .player_card
    h3 
      a href="/players/#{player.username}" #{player.username.capitalize}

app/views/players/part/_activity.html.slim
h2 Activity
- @activities.each do |activity|
  - # Activity.event is a descriptive verb (e.g. played, added, achieved)
  - # Activity.description is the description of the event
  h4 #{activity.event} #{activity.description} with #{'peoples'}
  p=Time.parse(activity.created_at.to_s).strftime('%H:%M %B %e %Y')
- if @activities.blank?
  p No activity to show.

app/views/players/part/_comrade_requests.slim
- unless @comrade_requests.blank?
  h2 Comrade Requests
  - @comrade_requests.each do |comrade|
    h4 <a href="/players/#{comrade.player.username}">#{comrade.player.username}</a> wants to be your comrade:
    p
      a href="#" Accept
      |  or 
      a href="#" Reject

app/views/players/part/_comrades.slim
h2 Comrades
- @comrades.each do |comrade|
  - player = Player.find(comrade.comrade_id) unless @player.id == comrade.comrade_id
  - player = Player.find(comrade.player_id) if @player.id == comrade.comrade_id
  h4
    a href="/players/#{player.username}" #{player.username}
  p Comrade since #{time_ago_in_words(comrade.updated_at)} ago.
- if @comrades.blank?
  p #{@player.username} has no comrades.

app/views/players/show.html.slim
h1 #{@player.username.capitalize}'s Profile
- if current_player && @player.id != current_player.id
  a href="#" Add as comrade
p Member since #{time_ago_in_words(@player.created_at)} ago.
p Last sign in was #{time_ago_in_words(@player.current_sign_in_at)} ago.

= render "players/part/comrades"
= render "players/part/comrade_requests"
= render "players/part/activity"